### ISSUE TITLE
Would support swagger ?

### ISSUE THREAD

**Issue by ghost** [fabriciocolombo/delphi-rest-client-api#82]
I was try to find Pascal Swagger support.
But I found nothing.
Then I try to do something for it, but has not progressed.

Would you support swagger?
This framework also try to support it,
https://github.com/danieleteti/delphimvcframework
but they have no help.

Thanks.

**Comment by RobertoSchneiders** [comment]
Can you provide more information about Pascal Swagger? project link? It is a api doc generator?

**Comment by 674395896** [comment]
Yes, it is an api doc generator.
Please look in this site: 
http://swagger.io/open-source-integrations/

Can you support that generate client classes by the api doc like generate datasnap client classes?
It is very useful.
Thanks.

**Comment by RobertoSchneiders** [comment]
Makes sense, we could support it. 

Do you plan to implement this?

**Comment by 674395896** [comment]
I want to do it , but I have no clue even I have read some info.

**Comment by RobertoSchneiders** [comment]
Ok, let's wait and see if any of the commiters want to work on this. We will need someone with some experience with Swagger.

**Comment by fabriciocolombo** [comment]
I think this is outside the scope of this project.
Swagger is focused on the API itself and your development cycle. It generate documentation and have a UI where you can interact with your API to evaluate. 

This library is just for consume the API (This library is just to consume the API (that could be backed by Swagger).

It make sense add support for Swagger in https://github.com/danieleteti/delphimvcframework, because you are creating an API, and you need this kind of features. There are already an opened issue: https://github.com/danieleteti/delphimvcframework/issues/38.
